### ISSUE TITLE
Fluidlogging Not Working

### ISSUE THREAD

**Issue by JustDesoroxxx** [juraj-hrivnak/Greenery#5]
Greenery Version: 1.12.2-2.0
Fluidlogged API Version: v1.8.1d-mc1.12.2

![image](https://user-images.githubusercontent.com/82710983/185723036-45301a80-f1e0-4d94-afa7-ab845f6f047e.png)

**Comment by juraj-hrivnak** [comment]
Any other mods you use with it? It works fine for me.

**Comment by JustDesoroxxx** [comment]
After investigation, I can confirm two things:

- The issue is only linked to world gen spawn (if I break and replace the plants the waterlogging works and update for the nearby plants too)
- The issue only happens with the latest version of Fluidlogged API which is v1.8.1d (The world gen spawned plants are water logged when using Fluidlogged API v1.8.1c)

**Comment by juraj-hrivnak** [comment]
There must’ve been some changes that broke it. I will try to fix this in the new update. Thanks for the report!

**Comment by jbredwards** [comment]
The only thing I did between updates was improve the config and remove unnecessary neighbor fluid block updates, so this is probably an issue with Fluidlogged API's chunk capabilities. For whatever reason I can't figure out how to get them load properly (server-side nor client-side), adding [this](https://github.com/CleanroomMC/Fluidlogged-API/blob/3667ee8636d76003ffa65530984073319d977d49/src/main/java/git/jbredwards/fluidlogged_api/mod/common/EventHandler.java#L65) magically got them to load client-side and server-side (genuinely no clue how), since then I've just kinda ignored the problem, I'll look into it again once I finish up the njarm2 rewrite. In the meantime you can try queuing neighbor fluid block updates when the kelp generates and see if that works, this will cause the water to flow into the kelp when the world is loaded, this is probably what was happening before so it should be fine for now.

**Comment by juraj-hrivnak** [comment]
@JustDesoroxxx I can't reproduce it. Can you try it again with Fluidlogged API v1.8.1e

**Comment by juraj-hrivnak** [comment]
I am closing it because I can not reproduce it, and the issue is stale.
